### ISSUE TITLE
In some cases, Z ordering of Player object matters

### ISSUE THREAD

**Issue by Earlz** [anwell/TappyPlane#3]
So, I ended up making a few mistakes laying out my scene following this tutorial, and basically my scene looked correct. After my player object respawned however, it would be behind the background, making the game slightly hard to play ;) 

Setting it the Z of the player object to -1 or whatever fixed this though. Just hard to figure out, being a Unity noob. Might be nice to mention this possible mistake in your tutorial

**Comment by anwell** [comment]
Good catch, I updated this repository to give the player a z index of -1 and threw it into the tutorial.
